language: ruby

rvm:
  - 2.1.7

branches:
  only:
      - master

before_script:
  - psql -c 'create database itedd_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

bundler_args: "--without development production"
